export enum OrderColumnsEnum {
  ID = 'id',
  NAME = 'name',
  SURNAME = 'surname',
  EMAIL = 'email',
  PHONE = 'phone',
  AGE = 'age',
  COURSE = 'course',
  COURSE_FORMAT = 'course_format',
  COURSE_TYPE = 'course_type',
  STATUS = 'status',
  CREATED_AT = 'created_at',
  SUM = 'sum',
  ALREADY_PAID = 'alreadyPaid',
}
